version: '3'

services:
  alexa_control:
    build: /alexa-controller-app
    container_name: alexa_control
    env_file:
      - ./.env
    environment:
      SET_REFRESH_TOKEN: "${SET_REFRESH_TOKEN}"
      
    # command: ["./alexa_remote_control.sh",  "-e",  'speak:<audio src="${AUDIO_SOURCE}"/>こんにちは!Windowsのコマンドプロンプトから、Alexaに話させてみました。']
